#!/bin/sh

# MISC

alias ls="ls -hN --color=auto --group-directories-first"
alias la="ls -a"
alias l="ls -la"
alias tarc="tar -czvf"
alias tarx="tar -xzvf"
alias cp="cp -v"
alias grep="grep --color=auto"
alias cls="clear && clear"
alias psg="ps -ef | grep -i"
alias yt="youtube-dl -i --add-metadata"

# GIT

alias g="git"

alias gl="git log --show-signature"
alias glom="gl origin/master.."

alias gc="git commit"

alias gr="git rebase"
alias grom="gr origin/master --autostash"
alias gromi="grom -i"

alias gf="git fetch"
alias gfa="gf -apt"

alias gs="git status"

alias gd="git diff"
alias gds="gd --staged"

alias ga="git add"
alias gap="ga -p"

alias gp="git push"
alias gpo="gp origin"
alias gpof="gpo --force-with-lease"

alias gbdag="gfa && git branch -vv | grep ': gone]' | sed -e 's/^[[:space:]]*//' > $TMPDIR/git-gone-branches && $EDITOR $TMPDIR/git-gone-branches && cat $TMPDIR/git-gone-branches | cut -d' ' -f1 | xargs git branch -vD"
