#!/bin/sh

export DOTFILES="$HOME/dotfiles"
export EDITOR='vim'
export TMPDIR='/tmp'
export CDPATH=".:$HOME/projects:$HOME/bookmarks"

export LESS=-R
export LESSHISTFILE=$HOME/.cache/less/history
export LESSHISTSIZE=1000
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
