" Fish doesn't play all that well with others
set shell=/bin/bash

let mapleader = "\<Space>"

call plug#begin('~/.vim/plugged')
Plug 'junegunn/goyo.vim'
Plug 'jreybert/vimagit'
call plug#end()

" disable arrow keys
nnoremap <Left>  :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up>    :echoe "Use k"<CR>
nnoremap <Down>  :echoe "Use j"<CR>

" map jk to ESC in insert mode
inoremap jk <esc>

" shorter split navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" german chars
imap :a ä
imap :u ü
imap :o ö
imap :A Ä
imap :U Ü
imap :O Ö
imap :s ß

" turn on Goyo distraction free writing
map <leader>f :Goyo<CR>

" run build script
map <leader>b :w! \| ./build.sh<CR>

" some basics
syntax on

set tabstop=4
set background=dark

set number
set relativenumber
set autoindent
set encoding=utf-8
set printencoding=utf-8

" sane splits
set splitright
set splitbelow

" permanent undo
set undodir=~/.cache/vim/undo
set undofile

set nocompatible " necessary for lots of cool stuff
set showcmd      " shows you what you are typing as a command

" proper search
set incsearch " highlight while searching
set ignorecase " case insensitive pattern matching
set smartcase  " override ignorecase if pattern contains uppercase
set gdefault " replace global (///g) as default

set runtimepath^=~/dotfiles/submodules/ctrlpvim
let g:ctrlp_custom_ignore = '\v[\/](node_modules|target|dist|build)|(\.(swp|ico|git|svn))$'

" enable autocompletion
set wildmode=longest,list,full

" delete trailing whitespace on save
autocmd BufWritePre * %s/\s\+$//e
