#!/bin/sh

if [ ! -f $1 ]
then
	echo "file not found: $1"
else
	if [ ! -f "$1.bak" ]
	then
		cp "$1" "$1.bak"
	else
		CNTR=1
		while [ -f "$1.bak$CNTR" ]
		do
			((CNTR++))
		done
		cp "$1" "$1.bak$CNTR"
	fi
fi

